### ISSUE TITLE
Question about the calculation of metrics

### ISSUE THREAD

**Issue by bugsuse** [amazon-research/earth-forecasting-transformer#3]
It's a very solid and interesting work! Thanks for your sharing the nice code!

I found that the arguments order of function `calc_seq_hits_misses_fas` at L144 seems inconsistent with the definition at L112.  This perhaps lead to errors in the calculation of some metrics (such as `pod`, `bias` and `sucr`).

[https://github.com/amazon-research/earth-forecasting-transformer/blob/9c18c5a0be9c1af686827a191217a6cccf57812b/src/earthformer/metrics/sevir.py#L112](url)

[https://github.com/amazon-research/earth-forecasting-transformer/blob/9c18c5a0be9c1af686827a191217a6cccf57812b/src/earthformer/metrics/sevir.py#L144](url)

**Comment by gaozhihan** [comment]
Thanks for your interest and reporting the error! We will submit a PR for fixing it. 
The [incorrect usage of `calc_seq_hits_misses_fas` at L144](https://github.com/amazon-research/earth-forecasting-transformer/blob/9c18c5a0be9c1af686827a191217a6cccf57812b/src/earthformer/metrics/sevir.py#L112) results in the reported `pod` to be the actual `sucr`, the reported `sucr` to be the actual `pod`. and the reported `bias` to be the actual `1/bias`. The [calculation of `CSI`](https://github.com/amazon-research/earth-forecasting-transformer/blob/9c18c5a0be9c1af686827a191217a6cccf57812b/src/earthformer/metrics/sevir.py#L104) is not affected.
We will also soon submitting PRs that add test-cases, inference examples with the pretrained model.

**Comment by sxjscience** [comment]
Really appreciate for pointing it out! @bugsuse

**Comment by bugsuse** [comment]
Happy to help! I have also learned many advanced usages from the nice and clean code you shared!
