### ISSUE TITLE
reproduce the results on ICAR-ENSO datasest

### ISSUE THREAD

**Issue by tianzhou2011** [amazon-research/earth-forecasting-transformer#5]
Dear authors
Thank you for the code release. It's very informative.  However, I wonder if there are some arguments I need to change to reproduce the ENSO's results. I run the train_cuboid_enso.py with cfg.yaml. it end up with NiNO_M:65.7, WM: 1.933 and mse:0.00272 far from the 0.7239,2.214,0.00255 reported in the paper; I also run a cfg.yaml with 8 global vectors, it gave even worse results compared to the original setting.

**Comment by gaozhihan** [comment]
Thanks for pointing it out. We have verified that training using the current default [cfg.yaml](https://github.com/amazon-research/earth-forecasting-transformer/blob/61cab363c8c15d98ecd40643d628303d0234096b/scripts/cuboid_transformer/enso/cfg.yaml) indeed results in suboptimal performance. Sorry for the inconvenience.
We have [reproduced our result](https://tensorboard.dev/experiment/Jwq47eRfRoqO8kv2qCRqdA/#scalars&_smoothingWeight=0)(C-Nino3.4-M $=0.7322$, C-Nino3.4-WM $=2.263$, $MSE = 2.596\times10^{-4}$) by simply changing the configs of batch_size (`total_batch_size: 64` and `micro_batch_size: 16`, or `total_batch_size: 64` and `micro_batch_size: 8`). In short, setting `total_batch_size: 64` in the [cfg.yaml](https://github.com/amazon-research/earth-forecasting-transformer/blob/main/scripts/cuboid_transformer/enso/cfg.yaml) should help.
Please feel free to contact us if you have any further questions. We will also soon submitting PRs that update training script, test-cases, inference examples with the pretrained model.

**Comment by tianzhou2011** [comment]
Thanks for your fixing.
